name: Pipeline

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Tests
        run: |
          cd src
          python -m unittest discover test
  deployment:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Fresh Clone & Repo Install
        uses: appleboy/ssh-action@master
        with:
          host: 35.174.123.14
          username: github-actions
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            rm -rf RebekahHeal_T2A3
            git clone https://github.com/rheal3/RebekahHeal_T2A3.git
            python3.8 -m venv /home/github-actions/RebekahHeal_T2A3/venv/
            source /home/github-actions/RebekahHeal_T2A3/venv/activate
            pip install -r /home/github-actions/RebekahHeal_T2A3/requirements.txt
