name: Pipeline

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Tests
        run: |
          python em unittest discover tests/
  deployment:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Fresh Clone & Repo Install
        uses: appleboy/ssh-action@master
        with:
          host: ###
          username: ###
          key: $###
          port: 22
          script: |
            rm -rf ###
            git clone ###
            python3.8 -m venv /home/###/###/venv
            /home/###/###/venv/bin/pip3.8 install -r /home/###/###/requirements.txt 
